CI: Test release workflow jobs

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -5,19 +5,15 @@ on:
     paths-ignore:
       - '**.md'
     branches:
-      - master
-      - 'release/**'
-    tags:
-      - '*'
+      - release-test
 permissions:
   contents: write
 concurrency:
   group: '${{ github.workflow }} @ ${{ github.ref }}'
-  cancel-in-progress: ${{ github.ref_type == 'tag' }}
+  cancel-in-progress: ${{ fromJSON(github.ref_type == 'tag') }}
 jobs:
   check-format:
     name: Check Formatting 🔍
-    if: github.ref_name == 'master'
     uses: ./.github/workflows/check-format.yaml
     permissions:
       contents: read
@@ -29,141 +25,20 @@ jobs:
     permissions:
       contents: read
 
-  compatibility-validation:
-    name: Validate Compatibility Data 🕵️
-    if: github.ref_name == 'master'
-    runs-on: ubuntu-22.04
-    permissions:
-      checks: write
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: Check for Changed Files ✅
-        uses: ./.github/actions/check-changes
-        id: checks
-        with:
-          baseRef: ${{ github.event.before }}
-          checkGlob: plugins/win-capture/data/*.json
-
-      - name: Check for Invalid Compatibility Data 📉
-        if: fromJSON(steps.checks.outputs.hasChangedFiles)
-        uses: ./.github/actions/compatibility-validator
-        with:
-          repositorySecret: ${{ github.token }}
-
-  services-validation:
-    name: Validate Service Data 🕵️
-    if: github.ref_name == 'master'
-    runs-on: ubuntu-22.04
-    permissions:
-      checks: write
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-
-      - name: Check for Changed Files ✅
-        uses: ./.github/actions/check-changes
-        id: checks
-        with:
-          baseRef: ${{ github.event.before }}
-          checkGlob: plugins/rtmp-services/data/*.json
-
-      - name: Check Services JSON Schema 📉
-        if: fromJSON(steps.checks.outputs.hasChangedFiles)
-        uses: ./.github/actions/services-validator
-        with:
-          repositorySecret: ${{ github.token }}
-          runSchemaChecks: true
-          runServiceChecks: false
-
-  upload-language-files:
-    name: Upload Language Files 🌐
-    if: github.repository_owner == 'obsproject' && github.ref_name == 'master'
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          submodules: recursive
-          fetch-depth: 0
-
-      - name: Check for Changed Files ✅
-        uses: ./.github/actions/check-changes
-        id: checks
-        with:
-          baseRef: ${{ github.event.before }}
-          checkGlob: '**/en-US.ini'
-
-      - name: Upload US English Language Files 🇺🇸
-        if: fromJSON(steps.checks.outputs.hasChangedFiles)
-        uses: obsproject/obs-crowdin-sync/upload@0.2.1
-        env:
-          CROWDIN_PAT: ${{ secrets.CROWDIN_SYNC_CROWDIN_PAT }}
-          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
-
   update-documentation:
     name: Update Documentation 📖
-    if: github.repository_owner == 'obsproject' && (github.ref_name == 'master' || github.ref_type == 'tag')
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
-      - name: Check for Changed Files ✅
-        if: github.ref_name != 'tag'
-        uses: ./.github/actions/check-changes
-        id: checks
-        with:
-          baseRef: ${{ github.event.before }}
-          checkGlob: '!(cmake*)'
-
       - uses: ./.github/actions/generate-docs
-        if: github.ref_type == 'tag' || fromJSON(steps.checks.outputs.hasChangedFiles)
         with:
-          disableLinkExtensions: ${{ github.ref_type == 'tag' }}
-
-  deploy-documentation:
-    name: Deploy Documentation to Cloudflare ☁️
-    if: github.repository_owner == 'obsproject' && github.ref_type == 'tag'
-    runs-on: ubuntu-22.04
-    needs: update-documentation
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - name: Get Commit Information 🆔
-        id: setup
-        run: |
-          : Get Commit Hash 🆔
-          echo "commitHash=${GITHUB_SHA:0:9}" >> $GITHUB_OUTPUT
-
-      - uses: actions/download-artifact@v3
-        with:
-          name: OBS Studio Docs (No Extensions) ${{ steps.setup.outputs.commitHash }}
-          path: docs
-
-      - name: Set Up Redirects 🔄
-        run: |
-          : Set Up Redirects 🔄
-          if [[ "${RUNNER_DEBUG}" ]]; then set -x; fi
-
-          echo "/previous/27.2 https://obsproject.com/docs/27.2 302" >> docs/_redirects
-          echo "/previous/:major.:minor https://:major-:minor.${{ vars.CF_PAGES_PROJECT }}.pages.dev 302" >> docs/_redirects
-
-      - name: Publish to Live Page
-        uses: cloudflare/wrangler-action@4c10c1822abba527d820b29e6333e7f5dac2cabd
-        with:
-          workingDirectory: docs
-          apiToken: ${{ secrets.CF_API_TOKEN }}
-          accountId: ${{ secrets.CF_ACCOUNT_ID }}
-          command: pages publish . --project-name=${{ vars.CF_PAGES_PROJECT }} --commit-hash='${{ steps.setup.outputs.commitHash }}'
+          disableLinkExtensions: true
 
   create-appcast:
     name: Create Sparkle Appcast 🎙️
-    if: github.repository_owner == 'obsproject' && github.ref_type == 'tag'
     runs-on: macos-13
     needs: build-project
     strategy:
@@ -221,7 +96,6 @@ jobs:
 
   create-release:
     name: Create Release 🛫
-    if: github.ref_type == 'tag'
     runs-on: ubuntu-22.04
     needs: build-project
     defaults:
@@ -296,18 +170,95 @@ jobs:
             echo "    ${file##*/}: $(sha256sum "${file}" | cut -d " " -f 1)" >> ${{ github.workspace }}/CHECKSUMS.txt
           done
 
-      - name: Create Release 🛫
-        if: fromJSON(steps.check.outputs.validTag)
-        id: create_release
-        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
+          echo "$(<CHECKSUMS.txt)"
+
+  flatpak-publish:
+    name: Publish to Flathub 📦
+    needs: create-release
+    runs-on: ubuntu-22.04
+    defaults:
+      run:
+        shell: bash
+    env:
+      FLATPAK_BUILD_PATH: flatpak_app/files/share
+    container:
+      image: bilelmoussaoui/flatpak-github-actions:kde-6.4
+      options: --privileged
+    strategy:
+      matrix:
+        branch: ${{ fromJSON('["beta", "stable"]') }}
+    steps:
+      - name: Set Up Environment 🔧
+        id: setup
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          : Set Up Environment 🔧
+          if [[ "${RUNNER_DEBUG}" ]]; then set -x; fi
+
+          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
+
+          dnf install -y -q gh
+          gh extension install actions/gh-actions-cache
+
+          cache_key='flatpak-builder-${{ hashFiles('build-aux/**/*.json') }}'
+          cache_ref='master'
+          read -r key size unit _ ref _ <<< \
+            "$(gh actions-cache list -B ${cache_ref} --key "${cache_key}-x86_64" | head -1)"
+
+          if [[ "${key}" ]]; then
+            echo "cacheHit=true" >> $GITHUB_OUTPUT
+          else
+            echo "cacheHit=false" >> $GITHUB_OUTPUT
+          fi
+
+          echo "cacheKey=${cache_key}" >> $GITHUB_OUTPUT
+          echo "commitHash=$(git rev-parse --short=9 HEAD)" >> $GITHUB_OUTPUT
+
+      - uses: actions/checkout@v3
         with:
-          draft: true
-          prerelease: ${{ fromJSON(steps.check.outputs.prerelease) }}
-          tag_name: ${{ steps.check.outputs.version }}
-          name: OBS Studio ${{ steps.check.outputs.version }}
-          body_path: ${{ github.workspace }}/CHECKSUMS.txt
-          files: |
-            ${{ github.workspace }}/OBS-Studio-${{ steps.check.outputs.version }}-macOS-*.dmg
-            ${{ github.workspace }}/OBS-Studio-${{ steps.check.outputs.version }}-macOS-*-dSYMs.tar.xz
-            ${{ github.workspace }}/OBS-Studio-${{ steps.check.outputs.version }}-Ubuntu-*.deb
-            ${{ github.workspace }}/OBS-Studio-${{ steps.check.outputs.version }}-Ubuntu-*.ddeb
+          submodules: recursive
+          fetch-depth: 0
+          set-safe-directory: ${{ github.workspace }}
+
+      - name: Build Flatpak Manifest
+        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
+        with:
+          bundle: obs-studio-${{ steps.setup.outputs.commitHash }}.flatpak
+          manifest-path: ${{ github.workspace }}/build-aux/com.obsproject.Studio.json
+          cache: ${{ fromJSON(steps.setup.outputs.cacheHit) }}
+          cache-key: ${{ steps.setup.outputs.cacheKey }}
+          mirror-screenshots-url: https://dl.flathub.org/repo/screenshots
+          branch: ${{ matrix.branch }}
+
+      - name: Validate AppStream
+        working-directory: ${{ env.FLATPAK_BUILD_PATH }}
+        run: |
+          : Validate AppStream
+          appstream-util validate appdata/com.obsproject.Studio.appdata.xml
+
+      - name: Verify Icon and Metadata in app-info
+        working-directory: ${{ env.FLATPAK_BUILD_PATH }}
+        run: |
+          : Verify Icon and Metadata in app-info
+          test -f app-info/icons/flatpak/128x128/com.obsproject.Studio.png || { echo "Missing 128x128 icon in app-info!"; exit 1; }
+          test -f app-info/xmls/com.obsproject.Studio.xml.gz || { echo "Missing com.obsproject.Studio.xml.gz in app-info!"; exit 1; }
+
+      - name: Commit Screenshots to OSTree Repository
+        run: |
+          : Commit Screenshots to OSTree Repository
+          ostree commit --repo=repo --canonical-permissions --branch=screenshots/x86_64 flatpak_app/screenshots
+
+  steam-upload:
+    name: Upload Steam Builds 🚂
+    needs: create-release
+    runs-on: macos-13
+    steps:
+      - uses: actions/checkout@v3
+      - uses: ./.github/actions/steam-upload
+        with:
+          steamSecret: ${{ secrets.STEAM_SHARED_SECRET }}
+          steamUser: ${{ secrets.STEAM_USER }}
+          steamPassword: ${{ secrets.STEAM_PASSWORD }}
+          workflowSecret: ${{ github.token }}
+          preview: true
